# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8929c344487d0e5a15c8be171e9c2dfdfae7b0714a85474367c0bbb7f66f08080b943af274029dbf3913aebe0746dea0c829675d2b772b5aa1d1e734d5ee7f18

test:
  secret_key_base: 0fdaf11d183d54756e7963c1c4efb52515375627f4f7fca0d1fb9be888ac9ebbf60e3120b737720315b8b626a019ee8b20b0e02282891565eee17d78245f67d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
